name: Test Datadog Universe Dashboard Changes

on:
  pull_request:
    types: [opened, closed, synchronize]
    paths:
      - 'global/datadog/dashboard/universe/**'

jobs:
  create-test-universe-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.1

      - name: Terraform Init
        run: terraform init
        working-directory: global/datadog/dashboard/universe

      - name: Set Branch Name as Workspace
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Create and Select Workspace
        run: |
          terraform workspace new ${{ env.BRANCH_NAME }} || terraform workspace select ${{ env.BRANCH_NAME }}
        working-directory: global/datadog/dashboard/universe

      - name: Apply Terraform Configuration
        run: terraform plan && terraform apply -auto-approve
        working-directory: global/datadog/dashboard/universe

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.1

      - name: Terraform Init
        run: terraform init
        working-directory: global/datadog/dashboard/universe

      - name: Set Branch Name as Workspace
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Select Workspace
        run: |
          terraform workspace select ${{ env.BRANCH_NAME }}
        working-directory: global/datadog/dashboard/universe

      - name: Destroy temporary Universe dashboard
        run: terraform destroy -auto-approve
        working-directory: global/datadog/dashboard/universe

      - name: Delete Workspace
        run: |
          terraform workspace select default
          terraform workspace delete ${{ env.BRANCH_NAME }}
        working-directory: global/datadog/dashboard/universe
